#!/usr/bin/env python3

"""a script to parse a detector from an INI file and then examine the antenna patterns
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os

import numpy as np

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

from argparse import ArgumentParser

### non-standard libraries
import gwdetectors

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('--config', default='network.ini', type=str)

parser.add_argument('-f', '--frequency', required=True, default=[], type=float, action='append',
    help='plot the detector responses at this frequency. Should be specified in Hz.')

parser.add_argument('--num-grid-points', default=100, type=int)

parser.add_argument('-v', '--verbose', default=False, action='store_true')

parser.add_argument('--color-map', default='coolwarm', type=str)
parser.add_argument('-o', '--output-dir', default='.', type=str)
parser.add_argument('-t', '--tag', default='', type=str)

args = parser.parse_args()

os.makedirs(args.output_dir, exist_ok=True)

if args.tag:
    args.tag = "_"+args.tag

#-------------------------------------------------

### load detector network from a config file

network = gwdetectors.parse(args.config, verbose=args.verbose, exit_on_exception=True)

#-------------------------------------------------

freqs = np.array(args.frequency, dtype=float)

t0 = 0.0
azimuth = np.linspace(-np.pi, +np.pi, 2*args.num_grid_points)
pole = np.linspace(0, np.pi, args.num_grid_points)
psi = 0.0

shape = (2*args.num_grid_points, args.num_grid_points)

AZIMUTH, POLE = np.meshgrid(azimuth, pole, indexing='ij')
AZIMUTH = AZIMUTH.flatten()
POLE = POLE.flatten()

PSI = np.ones_like(POLE, dtype=float)*psi

for detector in network.detectors:
    if args.verbose:
        print('computing detector response for : '+detector.name)

    fp, fx = detector.response(freqs, t0, AZIMUTH, POLE, PSI, coord='geographic')

    for fnd, freq in enumerate(freqs):
        if args.verbose:
            print('  plotting freq=%.3f Hz'%(freq))

#        fp, fx = detector.response(freq, t0, AZIMUTH, POLE, PSI, coord='geographic')
#        Fp = np.transpose(fp.reshape(shape))
#        Fx = np.transpose(fx.reshape(shape))

        Fp = np.transpose(fp[fnd].reshape(shape))
        Fx = np.transpose(fx[fnd].reshape(shape))

        fig = plt.figure(figsize=(8.0, 3.5))

        axp_amp = plt.subplot(2,3,1, projection='mollweide')
        axp_phs = plt.subplot(2,3,4, projection='mollweide')

        axx_amp = plt.subplot(2,3,2, projection='mollweide')
        axx_phs = plt.subplot(2,3,5, projection='mollweide')

        ax_amp = plt.subplot(1,3,3, projection='mollweide')

        # plot detector response

        axp_amp.pcolormesh(
            azimuth,
            0.5*np.pi - pole,
            np.abs(Fp),
#            vmin=0,
#            vmax=+1,
            rasterized=True,
            cmap=args.color_map,
        )

        axp_phs.pcolormesh(
            azimuth,
            0.5*np.pi - pole,
            np.arctan2(Fp.imag, Fp.real),
#            vmin=-np.pi,
#            vmax=+np.pi,
            rasterized=True,
            cmap=args.color_map,
        )

        axx_amp.pcolormesh(
            azimuth,
            0.5*np.pi - pole,
            np.abs(Fx),
#            vmin=0,
#            vmax=+1,
            rasterized=True,
            cmap=args.color_map,
        )

        axx_phs.pcolormesh(
            azimuth,
            0.5*np.pi - pole,
            np.arctan2(Fx.imag, Fx.real),
#            vmin=-np.pi,
#            vmax=+np.pi,
            rasterized=True,
            cmap=args.color_map,
        )

        ax_amp.pcolormesh(
            azimuth,
            0.5*np.pi - pole,
            (np.abs(Fp)**2 + np.abs(Fx)**2)**0.5,
#            vmin=0,
#            vmax=+1,
            rasterized=True,
            cmap=args.color_map,
        )

        # plot arm directions

        for arm in detector.arms:
            nx, ny, nz = np.array(arm)/np.sum(np.array(arm)**2)**0.5
            p = np.arccos(nz)
            a = np.arctan2(ny, nx)

            for ax in fig.axes:
                ax.plot(a, 0.5*np.pi-p, marker='o', markeredgecolor='k', markerfacecolor='none')

        # decorate
        axp_amp.set_title('$|F_+|$')
        axp_phs.set_title('arg $F_+$')
        axx_amp.set_title('$|F_\\times|$')
        axx_phs.set_title('arg $F_\\times$')
        ax_amp.set_title('$\sqrt{|F_+|^2 + |F_\\times|^2}$')

        for ax in fig.axes:
            ax.grid(True)
            plt.setp(ax.get_xticklabels(), visible=False)
            plt.setp(ax.get_yticklabels(), visible=False)

        fig.suptitle('%.3f Hz'%freq)

        fig.text(0.95, 0.05, '$\psi=%.3f$'%psi, ha='right', va='bottom')

        plt.subplots_adjust(
            left=0.05,
            right=0.95,
            bottom=0.05,
            top=0.90,
            hspace=0.05,
            wspace=0.20,
        )

        # save
        figname = os.path.join(
            args.output_dir,
            os.path.basename(__file__)+args.tag+('-%s'%detector.name)+('-%.3f'%freq).replace('.','d') + '.png'
        )
        if args.verbose:
            print('    saving : '+figname)
        fig.savefig(figname)
        plt.close(fig)
